<?php

/**
 * @file
 * JCL Collapse module functions.
 */

/**
 * Implements hook_init().
 */
function jcl_collapse_init() {
	drupal_add_js(drupal_get_path('module', 'jcl_collapse') . '/js/jcl_collapse.js');
}

/**
* Implements hook_theme().
*/
function jcl_collapse_theme($existing, $type, $theme, $path) {
	return array (
		'views_view__collapsible_list' => array (
		// 'variables' => array('view' => NULL,),
		'template' => 'views-view--collapsible-list' ,
		'base hook' => 'views_view',
		'path' => drupal_get_path('module', 'jcl_collapse') . '/templates',
		),
	);
}

/**
* Implementation of hook_views_api().
*/
function jcl_collapse_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'jcl_collapse'),
  );
}
 
// // 3.
// // Views export creates code that you have to paste in this function.
// /**
//  * Implementation of hook_views_default_views().
//  */
// function jcl_collapse_views_default_views() {
// 	// setup the default view
// 	$view = new view();
// 	$view->name = 'collapsible_list';
// 	$view->description = '';
// 	$view->tag = 'default';
// 	$view->base_table = 'node';
// 	$view->human_name = 'Collapsible list';
// 	$view->core = 7;
// 	$view->api_version = '3.0';
// 	$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */

// 	/* Display: Master */
// 	$handler = $view->new_display('default', 'Master', 'default');
// 	$handler->display->display_options['use_more_always'] = FALSE;
// 	$handler->display->display_options['access']['type'] = 'perm';
// 	$handler->display->display_options['cache']['type'] = 'none';
// 	$handler->display->display_options['query']['type'] = 'views_query';
// 	$handler->display->display_options['exposed_form']['type'] = 'basic';
// 	$handler->display->display_options['pager']['type'] = 'none';
// 	$handler->display->display_options['pager']['options']['offset'] = '0';
// 	$handler->display->display_options['style_plugin'] = 'default';
// 	$handler->display->display_options['style_options']['default_row_class'] = FALSE;
// 	$handler->display->display_options['style_options']['row_class_special'] = FALSE;
// 	$handler->display->display_options['row_plugin'] = 'fields';
// 	$handler->display->display_options['row_options']['hide_empty'] = TRUE;
// 	$handler->display->display_options['row_options']['default_field_elements'] = FALSE;
// 	/* Field: (X) Content: Title */
// 	$handler->display->display_options['fields']['title']['id'] = 'title';
// 	$handler->display->display_options['fields']['title']['table'] = 'node';
// 	$handler->display->display_options['fields']['title']['field'] = 'title';
// 	$handler->display->display_options['fields']['title']['ui_name'] = '(X) Content: Title';
// 	$handler->display->display_options['fields']['title']['label'] = '';
// 	$handler->display->display_options['fields']['title']['exclude'] = TRUE;
// 	$handler->display->display_options['fields']['title']['alter']['word_boundary'] = FALSE;
// 	$handler->display->display_options['fields']['title']['alter']['ellipsis'] = FALSE;
// 	$handler->display->display_options['fields']['title']['element_label_colon'] = FALSE;
// 	$handler->display->display_options['fields']['title']['link_to_node'] = FALSE;
// 	/* Field: (X) Content: Link */
// 	$handler->display->display_options['fields']['field_collapsible_link']['id'] = 'field_collapsible_link';
// 	$handler->display->display_options['fields']['field_collapsible_link']['table'] = 'field_data_field_collapsible_link';
// 	$handler->display->display_options['fields']['field_collapsible_link']['field'] = 'field_collapsible_link';
// 	$handler->display->display_options['fields']['field_collapsible_link']['ui_name'] = '(X) Content: Link';
// 	$handler->display->display_options['fields']['field_collapsible_link']['label'] = '';
// 	$handler->display->display_options['fields']['field_collapsible_link']['exclude'] = TRUE;
// 	$handler->display->display_options['fields']['field_collapsible_link']['alter']['alter_text'] = TRUE;
// 	$handler->display->display_options['fields']['field_collapsible_link']['alter']['text'] = '<div class="jcl-menu-item"><a href="[field_collapsible_link-url]">[field_collapsible_link-title]</a></div>';
// 	$handler->display->display_options['fields']['field_collapsible_link']['element_label_colon'] = FALSE;
// 	$handler->display->display_options['fields']['field_collapsible_link']['element_default_classes'] = FALSE;
// 	$handler->display->display_options['fields']['field_collapsible_link']['click_sort_column'] = 'url';
// 	$handler->display->display_options['fields']['field_collapsible_link']['delta_offset'] = '0';
// 	$handler->display->display_options['fields']['field_collapsible_link']['separator'] = '';
// 	/* Field: (X) Content: Class */
// 	$handler->display->display_options['fields']['field_collapsible_class']['id'] = 'field_collapsible_class';
// 	$handler->display->display_options['fields']['field_collapsible_class']['table'] = 'field_data_field_collapsible_class';
// 	$handler->display->display_options['fields']['field_collapsible_class']['field'] = 'field_collapsible_class';
// 	$handler->display->display_options['fields']['field_collapsible_class']['ui_name'] = '(X) Content: Class';
// 	$handler->display->display_options['fields']['field_collapsible_class']['label'] = '';
// 	$handler->display->display_options['fields']['field_collapsible_class']['exclude'] = TRUE;
// 	$handler->display->display_options['fields']['field_collapsible_class']['alter']['text'] = '<div class="collapsible jcl-menu collapsed [field_collapsible_class-value]">
// 	  <legend>[title]</legend><div class="jcl-menu-wrapper">
// 	     <div>[field_collapsible_link]</div>
// 	  </div>
// 	</div>';
// 	$handler->display->display_options['fields']['field_collapsible_class']['element_label_colon'] = FALSE;
// 	$handler->display->display_options['fields']['field_collapsible_class']['delta_offset'] = '0';
// 	$handler->display->display_options['fields']['field_collapsible_class']['separator'] = ' ';
// 	/* Field: Global: Custom text */
// 	$handler->display->display_options['fields']['nothing']['id'] = 'nothing';
// 	$handler->display->display_options['fields']['nothing']['table'] = 'views';
// 	$handler->display->display_options['fields']['nothing']['field'] = 'nothing';
// 	$handler->display->display_options['fields']['nothing']['label'] = '';
// 	$handler->display->display_options['fields']['nothing']['alter']['text'] = '<div class="collapsible jcl-menu collapsed [field_collapsible_class]">
// 	  <div class="legend">[title]</div>
// 	    <div class="jcl-menu-wrapper">
// 	      [field_collapsible_link]
// 	    </div>
// 	</div>';
// 	$handler->display->display_options['fields']['nothing']['element_label_colon'] = FALSE;
// 	$handler->display->display_options['fields']['nothing']['element_default_classes'] = FALSE;
// 	/* Sort criterion: Content: Weight (field_collapsible_weight) */
// 	$handler->display->display_options['sorts']['field_collapsible_weight_value']['id'] = 'field_collapsible_weight_value';
// 	$handler->display->display_options['sorts']['field_collapsible_weight_value']['table'] = 'field_data_field_collapsible_weight';
// 	$handler->display->display_options['sorts']['field_collapsible_weight_value']['field'] = 'field_collapsible_weight_value';
// 	/* Filter criterion: Content: Published */
// 	$handler->display->display_options['filters']['status']['id'] = 'status';
// 	$handler->display->display_options['filters']['status']['table'] = 'node';
// 	$handler->display->display_options['filters']['status']['field'] = 'status';
// 	$handler->display->display_options['filters']['status']['value'] = 1;
// 	$handler->display->display_options['filters']['status']['group'] = 1;
// 	$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
// 	/* Filter criterion: Content: Type */
// 	$handler->display->display_options['filters']['type']['id'] = 'type';
// 	$handler->display->display_options['filters']['type']['table'] = 'node';
// 	$handler->display->display_options['filters']['type']['field'] = 'type';
// 	$handler->display->display_options['filters']['type']['value'] = array(
// 	  'collapsible_menu' => 'collapsible_menu',
// 	);
// 	$handler->display->display_options['filters']['type']['group'] = 1;

// 	/* Display: Birth to Six buttons */
// 	$handler = $view->new_display('block', 'Birth to Six buttons', 'block_1');
// 	$handler->display->display_options['defaults']['header'] = FALSE;
// 	/* Header: Global: Text area */
// 	$handler->display->display_options['header']['area']['id'] = 'area';
// 	$handler->display->display_options['header']['area']['table'] = 'views';
// 	$handler->display->display_options['header']['area']['field'] = 'area';
// 	$handler->display->display_options['header']['area']['label'] = 'Header';
// 	$handler->display->display_options['header']['area']['content'] = '<h2>Books We Recommend</h2>';
// 	$handler->display->display_options['header']['area']['format'] = 'full_html';
// 	$handler->display->display_options['defaults']['filter_groups'] = FALSE;
// 	$handler->display->display_options['defaults']['filters'] = FALSE;
// 	/* Filter criterion: Content: Published */
// 	$handler->display->display_options['filters']['status']['id'] = 'status';
// 	$handler->display->display_options['filters']['status']['table'] = 'node';
// 	$handler->display->display_options['filters']['status']['field'] = 'status';
// 	$handler->display->display_options['filters']['status']['value'] = 1;
// 	$handler->display->display_options['filters']['status']['group'] = 1;
// 	$handler->display->display_options['filters']['status']['expose']['operator'] = FALSE;
// 	/* Filter criterion: Content: Type */
// 	$handler->display->display_options['filters']['type']['id'] = 'type';
// 	$handler->display->display_options['filters']['type']['table'] = 'node';
// 	$handler->display->display_options['filters']['type']['field'] = 'type';
// 	$handler->display->display_options['filters']['type']['value'] = array(
// 	  'collapsible_menu' => 'collapsible_menu',
// 	);
// 	$handler->display->display_options['filters']['type']['group'] = 1;
// 	/* Filter criterion: Content: Location (field_collapsible_location) */
// 	$handler->display->display_options['filters']['field_collapsible_location_value']['id'] = 'field_collapsible_location_value';
// 	$handler->display->display_options['filters']['field_collapsible_location_value']['table'] = 'field_data_field_collapsible_location';
// 	$handler->display->display_options['filters']['field_collapsible_location_value']['field'] = 'field_collapsible_location_value';
// 	$handler->display->display_options['filters']['field_collapsible_location_value']['value'] = 'birth-to-six';
 
// 	$views[$view->name] = $view;
// 	return $views;
// }