last_optimize: 0
autocomplete_max_occurrences: 0.9
index_prefix: ''
http_get_max_length: 4000
cron_action: spellcheck
site_hash: ''
_core:
  default_config_hash: gmtmSf_Xa5SX0JY2QtJNOkvsFiq1J7fHoJoixL15ni8
